# ===================================
#  Import/Export Behavior Config
# ===================================

import:
    # Page title
    title: Import Customers

    # Import List Column configuration
    list: $/responsiv/user/models/customer/columns-import.yaml

    # Import Form Field configuration
    form: $/responsiv/user/models/customer/fields-import.yaml

    # Import Model class
    modelClass: RainLab\Blog\Models\PostImport

    # Redirect when finished
    redirect: user/users

    # Required permissions
    # permissions: user.access_import_export

export:
    # Page title
    title: Export Customers

    # Output file name
    fileName: users.csv

    # Export List Column configuration
    list: $/responsiv/user/models/customer/columns-export.yaml

    # Export Model class
    modelClass: RainLab\Blog\Models\PostExport

    # Redirect when finished
    redirect: user/users

    # Required permissions
    # permissions: user.access_import_export
