
navigation:
    Getting Started:
        introduction: "Introduction"
        events: "Events"

    Components:
        component-session: "Session"
        component-account: "Account"
        component-authentication: "Authentication"
        component-registration: "Registration"
        component-reset-password: "Reset Password"

    Services:
        auth-manager: "Auth Manager"
        auth-impersonation: "Impersonation"
        auth-bearer-tokens: "Bearer Tokens"
